Feature - Only populates certain fields in resources.json if slug is ulb
unfoldingWord-dev/uw_tools pull request #17
Opened 2017-01-04 16:58 UTC by richmahn

Now the resources.json file should be empty for checking_questions, tw_cat, terms and notes unless the slug is 'ulb'

2017-01-05 13:45 UTC, phillip-hopper requested changes
We need unit tests to show the information is there for ULB but not UDB.

2017-01-09 13:49 UTC, phillip-hopper commented
Looking good @richmahn. Now it needs a test to show the fields are NOT blank for ULB, and that they are blank for both ULB and UDB in another language.

2017-01-10 20:17 UTC, richmahn commented
Ok, test for ULB to have the URLs is added.

2017-01-10 20:20 UTC, phillip-hopper approved these changes

2017-01-10 20:20 UTC, merged